---
title: "West Side Aphid Whitefly 2022"
output: html_document
date: '2022-12-16'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
getwd()
```


```{r}
library(tidyverse)
library(readxl)

WSAphWf2022.1 <-read_excel ("C:/Users/bachhami/Box Sync/UCDavis_Buddhi/AphidWhiteflyData/westside_aphid_wf2022/West_Side_Aphid_Wf_Data2022.forR.xlsx") 

library(dplyr)
WSAphWf2022.1 <- mutate(WSAphWf2022.1, Date = as.Date(Date, origin = "15/8/2022"))

head (WSAphWf2022.1)


WSAphWf2022 <- WSAphWf2022.1 %>%
  filter (DAT %in% c("20-DAT-2","14-DAT-2", "7-DAT-2","2-DAT-2","13","7","2"))

head (WSAphWf2022)
```

```{r}
WSAphWf2022$DAT<-as.factor(WSAphWf2022$DAT) 
WSAphWf2022$TRT<-as.factor(WSAphWf2022$TRT)
WSAphWf2022$Product<-as.factor(WSAphWf2022$Product)
WSAphWf2022$Block<-as.factor(WSAphWf2022$Block)
```

```{r}
library(dplyr)

WSAphWf2022.2<-WSAphWf2022 %>%
  mutate(DAT = case_when(
    DAT == '0' ~ '0',
    DAT =='2' ~ '2-DAT1', 
    DAT == '7' ~ '7-DAT1',
    DAT == '13' ~ '13-DAT1',
    DAT == '2-DAT-2' ~ '2-DAT2',
    DAT == '7-DAT-2' ~ '7-DAT2',
    DAT == '14-DAT-2' ~ '14-DAT2',
    DAT == '20-DAT-2' ~ '20-DAT2'))

head (WSAphWf2022.2)
tail (WSAphWf2022.2)
```


```{r}
library(plyr)
#summary whitefly
summaryWf<- ddply(WSAphWf2022.2, c("DAT","Product","TRT", "App"), summarise,
                  N2    = sum(!is.na(Total_WFnymph_per_leaf)),
                  WfNym.Mean = mean(Total_WFnymph_per_leaf, na.rm=TRUE),
                  WfNymSD   = sd(Total_WFnymph_per_leaf, na.rm=TRUE),
                  WfNySE   = WfNymSD / sqrt(N2),
                  WfNy.Sum = sum(Total_WFnymph_per_leaf, na.rm=TRUE),
                  
                  N3    = sum(!is.na(WF_adult_per_leaf)),
                  WfAd.Mean = mean(WF_adult_per_leaf, na.rm=TRUE),
                  WfAdSD   = sd(WF_adult_per_leaf, na.rm=TRUE),
                  WfAdSE   = WfAdSD / sqrt(N3),
                  WfAd.Sum = sum(WF_adult_per_leaf, na.rm=TRUE))

summaryWf


## Whitefly after treatment
SummedWF<- ddply(WSAphWf2022.2, c("Product","TRT","Block"), summarise,
                 WfNym.Sum = sum(Total_WFnymph_per_leaf, na.rm=TRUE),
                 WfAd.Sum = sum(WF_adult_per_leaf, na.rm=TRUE))


SummedWF

SummedWF.Avg<- ddply(SummedWF, c("Product","TRT"), summarise,
                     N = sum(!is.na(WfNym.Sum)),
                     WfNym.SumAvg = mean(WfNym.Sum, na.rm=TRUE),
                     WfNym.SumSD   = sd(WfNym.Sum, na.rm=TRUE),
                     WfNym.SumSE   = WfNym.SumSD / sqrt(N),
                     WfAd.SumAvg = mean(WfAd.Sum, na.rm=TRUE),
                     WfAd.SumSD   = sd(WfAd.Sum, na.rm=TRUE),
                     WfAd.SumSE   = WfAd.SumSD / sqrt(N) ) 

SummedWF.Avg
```

```{r}
### Whitefly summary graphs
#### ALL dates

WFNymChart <- summaryWf %>%
  mutate (DAT = fct_relevel(DAT, "20-DAT2","14-DAT2", "7-DAT2","2-DAT2","13-DAT1","7-DAT1","2-DAT1")) %>%
  ggplot(aes(fill=DAT,y=WfNym.Mean, x=Product))+
  geom_bar(position="stack",stat="identity")+ 
  theme_bw()+
  theme(axis.text.x=element_text(angle=90)) 
  
WFNymChart
```

```{r}
#Whitefly adult summary (field count)
WFAdChart <- summaryWf %>%
  mutate (DAT = fct_relevel(DAT, "20-DAT2","14-DAT2", "7-DAT2","2-DAT2","13-DAT1","7-DAT1","2-DAT1")) %>%
  ggplot(aes(fill=DAT,y=WfAd.Mean, x=Product))+
  geom_bar(position="stack",stat="identity")+ 
  scale_fill_manual("DAT", values = c("20-DAT2" = "black","14-DAT2" = "orange", "7-DAT2" = "blue","2-DAT2" = "lightgreen","13-DAT1" = "red","7-DAT1" = "purple","2-DAT1" = "grey")) + 
  theme_bw()+
  theme(axis.text.x=element_text(angle=90)) 

WFAdChart
```

```{r}
library(plyr)
#summary aphid
summary_T_aphid<- ddply(WSAphWf2022.2, c("DAT","Product","TRT"), summarise,
                  N4    = sum(!is.na(Total_Aphid_pre_leaf)),
                  TAphid.Mean = mean(Total_Aphid_pre_leaf, na.rm=TRUE),
                  TAphidSD   = sd(Total_Aphid_pre_leaf, na.rm=TRUE),
                  TAphidSE   = TAphidSD / sqrt(N4),
                  TAphid.Sum = sum(Total_Aphid_pre_leaf, na.rm=TRUE))
                  
                  
summary_T_aphid


## Total Aphid after treatment
SummedTAphid<- ddply(WSAphWf2022.2, c("Product","TRT","Block"), summarise,
                 TAphid.Sum = sum(Total_Aphid_pre_leaf, na.rm=TRUE)
                 )


SummedTAphid

#Adult summary without blocks

SummedTAphid.Avg<- ddply(SummedTAphid, c("Product","TRT"), summarise,
                     N = sum(!is.na(TAphid.Sum)),
                     TAphid.SumAvg = mean(TAphid.Sum, na.rm=TRUE),
                     TAphid.SumSD   = sd(TAphid.Sum, na.rm=TRUE),
                     TAphid.SumSE   =  TAphid.SumSD / sqrt(N)
                     ) 

SummedTAphid.Avg
```

```{r}
#Total Aphid chart
TAphidhart <- summary_T_aphid %>%
  mutate (DAT = fct_relevel(DAT, "20-DAT2","14-DAT2", "7-DAT2","2-DAT2","13-DAT1","7-DAT1","2-DAT1")) %>%
  ggplot(aes(fill=DAT,y=TAphid.Mean, x=Product))+
  geom_bar(position="stack",stat="identity")+ 
  theme_bw()+
  theme(axis.text.x=element_text(angle=90)) 

TAphidhart
```

```{r}
# For DPR 
# Selecting Sefina, pqz, sivanto, assail, untreated

dpr_data2022 <- WSAphWf2022.2 %>%
  filter (TrialSet %in%c("Untreated", "DPR"))
dpr_data2022
```

```{r}
#summary whitefly
summaryWf_dpr<- ddply(dpr_data2022, c("DAT","Product","TRT", "DPR_Label", "App"), summarise,
                  N2    = sum(!is.na(Total_WFnymph_per_leaf)),
                  WfNym.Mean = mean(Total_WFnymph_per_leaf, na.rm=TRUE),
                  WfNymSD   = sd(Total_WFnymph_per_leaf, na.rm=TRUE),
                  WfNySE   = WfNymSD / sqrt(N2),
                  WfNy.Sum = sum(Total_WFnymph_per_leaf, na.rm=TRUE),
                  
                  N3    = sum(!is.na(WF_adult_per_leaf)),
                  WfAd.Mean = mean(WF_adult_per_leaf, na.rm=TRUE),
                  WfAdSD   = sd(WF_adult_per_leaf, na.rm=TRUE),
                  WfAdSE   = WfAdSD / sqrt(N3),
                  WfAd.Sum = sum(WF_adult_per_leaf, na.rm=TRUE))

summaryWf_dpr


## Whitefly after treatment
SummedWF_dpr<- ddply(dpr_data2022, c("Product","TRT","Block", "DPR_Label"), summarise,
                 WfNym.Sum = sum(Total_WFnymph_per_leaf, na.rm=TRUE),
                 WfAd.Sum = sum(WF_adult_per_leaf, na.rm=TRUE))


SummedWF_dpr

SummedWF_dpr.Avg<- ddply(SummedWF_dpr, c("Product","TRT", "DPR_Label"), summarise,
                     N = sum(!is.na(WfNym.Sum)),
                     WfNym.SumAvg = mean(WfNym.Sum, na.rm=TRUE),
                     WfNym.SumSD   = sd(WfNym.Sum, na.rm=TRUE),
                     WfNym.SumSE   = WfNym.SumSD / sqrt(N),
                     WfAd.SumAvg = mean(WfAd.Sum, na.rm=TRUE),
                     WfAd.SumSD   = sd(WfAd.Sum, na.rm=TRUE),
                     WfAd.SumSE   = WfAd.SumSD / sqrt(N) ) 

SummedWF_dpr.Avg
```

```{r}
#WF nymphs

WFNymChart_dpr_2022 <- summaryWf_dpr %>%
  mutate (DAT = fct_relevel(DAT, "20-DAT2","14-DAT2", "7-DAT2","2-DAT2","13-DAT1","7-DAT1","2-DAT1")) %>%
  ggplot(aes(fill=DAT,y=WfNym.Mean, x=DPR_Label))+
  geom_bar(position="stack",stat="identity")+geom_bar(position="stack",stat="identity")+ 
  geom_bar(position="stack",stat="identity",color="#333333",size=.1)+
  scale_fill_brewer(palette = "Spectral")+
  theme_classic()+
  theme(axis.text.x=element_text(angle=60, hjust=0.99))+
  theme(text=element_text(size=15))+labs(fill = "DAT")+
  theme(axis.text.x=element_text(color="#000000", size=12),
        axis.text.y=element_text(color="#000000", size=12))+
  ylab("Avg. whitefly nymphs (per leaf)")+
  xlab("") 

WFNymChart_dpr_2022 
ggsave(file="WFNymChart_dpr_2022.jpg", width=8, height=6, dpi=600)
```

```{r}
# For DPR 
# whitefly adult
 
WFAdChart_dpr_2022 <- summaryWf_dpr %>%
  mutate (DAT = fct_relevel(DAT, "20-DAT2","14-DAT2", "7-DAT2","2-DAT2","13-DAT1","7-DAT1","2-DAT1")) %>%
  ggplot(aes(fill=DAT,y=WfAd.Mean, x=DPR_Label))+
  geom_bar(position="stack",stat="identity")+ 
  geom_bar(position="stack",stat="identity",color="#333333",size=.1)+
  scale_fill_brewer(palette = "Spectral")+
  theme_classic()+
  theme(axis.text.x=element_text(angle=60, hjust=0.99))+
  theme(text=element_text(size=15))+labs(fill = "DAT")+
  theme(axis.text.x=element_text(color="#000000", size=12),
        axis.text.y=element_text(color="#000000", size=12))+
  ylab("Avg. whitefly adults (per leaf)")+
  xlab("") 

WFAdChart_dpr_2022 
ggsave(file="WFAdChart_dpr_2022.jpg", width=8, height=6, dpi=600)
```

```{r}
#summary aphid
summary_T_aphid_dpr<- ddply(dpr_data2022, c("DAT","Product","TRT", "DPR_Label", "App"), summarise,
                  N4    = sum(!is.na(Total_Aphid_pre_leaf)),
                  TAphid.Mean = mean(Total_Aphid_pre_leaf, na.rm=TRUE),
                  TAphidSD   = sd(Total_Aphid_pre_leaf, na.rm=TRUE),
                  TAphidSE   = TAphidSD / sqrt(N4),
                  TAphid.Sum = sum(Total_Aphid_pre_leaf, na.rm=TRUE))
                  
                  
summary_T_aphid_dpr


## Total Aphid after treatment
SummedTAphid_dpr<- ddply(dpr_data2022, c("Product","TRT","Block", "DPR_Label", "App"), summarise,
                 TAphid.Sum = sum(Total_Aphid_pre_leaf, na.rm=TRUE)
                 )


SummedTAphid_dpr

#Adult summary without blocks

SummedTAphid_dpr.Avg<- ddply(SummedTAphid_dpr, c("Product","TRT", "DPR_Label"), summarise,
                     N = sum(!is.na(TAphid.Sum)),
                     TAphid.SumAvg = mean(TAphid.Sum, na.rm=TRUE),
                     TAphid.SumSD   = sd(TAphid.Sum, na.rm=TRUE),
                     TAphid.SumSE   =  TAphid.SumSD / sqrt(N)
                     ) 

SummedTAphid_dpr.Avg
```

```{r, include=TRUE,echo=TRUE,warning=FALSE}
# For DPR 

TAphidhart_dpr_2022 <- summary_T_aphid_dpr %>%
  mutate (DAT = fct_relevel(DAT, "20-DAT2","14-DAT2", "7-DAT2","2-DAT2","13-DAT1","7-DAT1","2-DAT1")) %>%
  ggplot(aes(fill=DAT,y=TAphid.Mean, x=DPR_Label))+
  geom_bar(position="stack",stat="identity",color="#333333",size=.1)+
    scale_fill_brewer(palette = "Spectral")+
  theme_classic()+
  theme(axis.text.x=element_text(angle=60, hjust=0.99))+
  theme(text=element_text(size=15))+labs(fill = "DAT")+
  theme(axis.text.x=element_text(color="#000000", size=12),
        axis.text.y=element_text(color="#000000", size=12))+
  ylab("Avg. Aphids (per leaf)")+
  xlab("")

TAphidhart_dpr_2022
ggsave(file="TAphidhart_dpr_2022.jpg", width=10, height=6, dpi=600)
```

```{r}

##Total aphid by product name for OSU
TAphidhart_dpr_2022_osu <- summary_T_aphid_dpr %>%
  mutate (DAT = fct_relevel(DAT, "20-DAT2","14-DAT2", "7-DAT2","2-DAT2","13-DAT1","7-DAT1","2-DAT1")) %>%
  ggplot(aes(fill=DAT,y=TAphid.Mean, x=Product))+
  geom_bar(position="stack",stat="identity",color="#333333",size=.1)+
    scale_fill_brewer(palette = "Spectral")+
  theme_classic()+
  theme(axis.text.x=element_text(angle=60, hjust=0.99))+
  theme(text=element_text(size=18))+labs(fill = "DAT")+
  theme(axis.text.x=element_text(color="#000000", size=16),
        axis.text.y=element_text(color="#000000", size=16))+
  ylab("Avg. Aphids (per leaf)")+
  xlab("")

TAphidhart_dpr_2022_osu
ggsave(file="TAphidhart_dpr_2022_osu.jpg", width=10, height=6, dpi=600)

```

```{r}
#whitefly nymphs for Osu
WFNymChart_dpr_2022_osu <- summaryWf_dpr %>%
  mutate (DAT = fct_relevel(DAT, "20-DAT2","14-DAT2", "7-DAT2","2-DAT2","13-DAT1","7-DAT1","2-DAT1")) %>%
  ggplot(aes(fill=DAT,y=WfNym.Mean, x=Product))+
  geom_bar(position="stack",stat="identity")+geom_bar(position="stack",stat="identity")+ 
  geom_bar(position="stack",stat="identity",color="#333333",size=.1)+
  scale_fill_brewer(palette = "Spectral")+
  theme_classic()+
  theme(axis.text.x=element_text(angle=60, hjust=0.99))+
  theme(text=element_text(size=18))+labs(fill = "DAT")+
  theme(axis.text.x=element_text(color="#000000", size=16),
        axis.text.y=element_text(color="#000000", size=16))+
  ylab("Avg. whitefly nymphs (per leaf)")+
  xlab("") 

WFNymChart_dpr_2022_osu 
ggsave(file="WFNymChart_dpr_2022_osu.jpg", width=10, height=8, dpi=600)
```

```{r}
WFNymChart_dpr_2022_osu_1 <- summaryWf_dpr %>%
  filter (App == "App1")%>%
  mutate (DAT = fct_relevel(DAT, "13-DAT1","7-DAT1","2-DAT1")) %>%
  ggplot(aes(fill=DAT,y=WfNym.Mean, x=Product))+
  geom_bar(position="stack",stat="identity")+geom_bar(position="stack",stat="identity")+ 
  geom_bar(position="stack",stat="identity",color="#333333",size=.1)+
  scale_fill_brewer(palette = "Spectral")+
  theme_classic()+
  theme(axis.text.x=element_text(angle=60, hjust=0.99))+
  theme(text=element_text(size=18))+labs(fill = "DAT")+
  theme(axis.text.x=element_text(color="#000000", size=16),
        axis.text.y=element_text(color="#000000", size=16))+
  ylab("Whitefly nymphs (per leaf)")+
  xlab("") 

WFNymChart_dpr_2022_osu_1 
ggsave(file="WFNymChart_dpr_2022_osu_1.jpg", width=10, height=8, dpi=600)
```

```{r}
##Total aphid by product name for OSU
TAphidhart_dpr_2022_osu.1 <- summary_T_aphid_dpr %>%
  filter (App == "App1")%>%
  mutate (DAT = fct_relevel(DAT, "13-DAT1","7-DAT1","2-DAT1")) %>%
  ggplot(aes(fill=DAT,y=TAphid.Mean, x=Product))+
  geom_bar(position="stack",stat="identity",color="#333333",size=.1)+
    scale_fill_brewer(palette = "Spectral")+
  theme_classic()+
  theme(axis.text.x=element_text(angle=60, hjust=0.99))+
  theme(text=element_text(size=18))+labs(fill = "DAT")+
  theme(axis.text.x=element_text(color="#000000", size=16),
        axis.text.y=element_text(color="#000000", size=16))+
  ylab("Avg. Aphids (per leaf)")+
  xlab("")

TAphidhart_dpr_2022_osu.1
ggsave(file="TAphidhart_dpr_2022_osu.1.jpg", width=10, height=6, dpi=600)



```

```{r}
##Total aphid by product name for OSU
TAphidhart_dpr_2022_osu.2 <- summary_T_aphid_dpr %>%
  filter (App == "App1")%>%
  mutate (DAT = fct_relevel(DAT, "2-DAT1","7-DAT1","13-DAT1"))

ggplot (TAphidhart_dpr_2022_osu.2, aes(y=TAphid.Mean, x=DAT,  color = Product)) +
  geom_line(aes (group = Product))


```

```{r}
WFNymChart_dpr_2022_osu.2 <- summaryWf_dpr %>%
  filter (App == "App1")%>%
  mutate (DAT = fct_relevel(DAT, "2-DAT1","7-DAT1","13-DAT1"))

cbPalette <- c("#000000", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7", "#999999", "#E69F00", "#56B4E9")

ggplot(WFNymChart_dpr_2022_osu.2, aes(fill=DAT,y=WfNym.Mean, x=DAT, color = Product))+
  geom_line(aes (group = Product), size = 1.5)+
  scale_colour_manual(values=cbPalette)

```

